### ISSUE TITLE
faithcanon user interface

### ISSUE THREAD

**Issue by nhc2000** [nhc2000/FaithCanon#1]
refer to mockups for instructions and last conversation.

**Comment by mehtaakshay2206** [comment]
1) Develop the 3 UI pages

[FaithCanonAmended.pdf](https://github.com/nhc2000/FaithCanon/files/1175524/FaithCanonAmended.pdf)

**Comment by mehtaakshay2206** [comment]
Estimation : 3 hrs

**Comment by nhc2000** [comment]
I approve 5hours to cover issues 1-4. First, I would like to see the index UI page with agreed corporate color code: Royal Purple before you create other two pages.

**Comment by nhc2000** [comment]
Per our phone conversation, the 7hours is approved. Go ahead and develop the index page for me to see. Remember Royal Purple is the color.

**Comment by mehtaakshay2206** [comment]
Done. Changes are deployed
