### ISSUE TITLE
Auth0 : Create new auth0 account for faithcanon

### ISSUE THREAD

**Issue by mehtaakshay2206** [nhc2000/FaithCanon#22]
- @nhc2000 Am waiting for you on this as before i was not able to login to the auth0 credentials you have provided me and you said you'll be contacting auth0 for it.
 - Once the above issue was resolved i can integrate new auth0 client.

**Comment by nhc2000** [comment]
I sent you the credential for nhc auth0 account. I did not see any development i.e  multifactor auth- push, sms, SSO integrations etc.
