### ISSUE TITLE
Index Page for faithcanon

### ISSUE THREAD

**Issue by mehtaakshay2206** [nhc2000/FaithCanon#5]
[FaithCanon.pdf.pdf](https://github.com/nhc2000/FaithCanon/files/1178826/FaithCanon.pdf.pdf)

**Comment by nhc2000** [comment]
The images on the index page are not good and I will have a better design later.  Go ahead with rest of work as agreed,

**Comment by mehtaakshay2206** [comment]
Done

**Comment by nhc2000** [comment]
The faithcanon logo is submerged in the royal purple background. Use the transparent logo in github.  It has to stand out.

**Comment by mehtaakshay2206** [comment]
@nhc2000 "faithcanonlogo.png" and "faithcansmall.png" both are same and they are transparent.
 - But what we need is the text "FaithCanon" in logo or whatever is in grey colour in logo should be in white or any other light colour so it can dominate against royal purple.
 - Currently the text colour was grey in logo so the grey colour was submerged in the royal purple background and its not visible.

**Comment by nhc2000** [comment]
for now we don't want to change the logo. Please remove and replace with white Text 'FaithCanon" in that sport. 
2. Put the logo left side (white area) and below the purple background.
3. Please repair this error message. I got it attempting to login with facebooks
4. Copy of the image of the error message is uploaded here and via skype as well

**Comment by mehtaakshay2206** [comment]
ok will make the changes.
 Estimation 30 mins to make changes and deploy

**Comment by nhc2000** [comment]
faithcanon.com is online now since yesterday when I configured the Route3 service. Check it out if you haven't.

**Comment by mehtaakshay2206** [comment]
@nhc2000 Done. Changes are deployed

**Comment by nhc2000** [comment]
Please remove faithbooks text under faithcanon logo when you click login. 
2. The family image (4 people lying down facing the sky, Dimension 269 x 369 pixels) is missing on the index page. You have faith image with the cross twice. Please replace the 1st top left faith with it.
3. Insert this scrolling scripture where the logo is on the index page and move logo below/down last image to center. 
Timothy 3:16 "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness".
4. Place logo in the logout page bottom center.
Let's discuss in the morning your next assignment when available.

**Comment by nhc2000** [comment]
Any third party API, please use our name rst communications llc with username as nhc2000. share password with me.

**Comment by nhc2000** [comment]
Creating a page or group. Ability to share group page/your page with friends and family. let reflect further on that.
2. Faithcanon.com has to have its own database.

**Comment by nhc2000** [comment]
your auth0 login info.
user: mehtaakshay22@gmail.com
password: aks2519

**Comment by mehtaakshay2206** [comment]
@nhc2000 Am not able to login to auth0 using the above credentials

**Comment by nhc2000** [comment]
let me check and revert

**Comment by nhc2000** [comment]
I was able to login. I just resent an invite to your email to login in mehtaakshay22@gmail.com with aks2519 as password. Let me know.

**Comment by mehtaakshay2206** [comment]
> Creating a page or group. Ability to share group page/your page with friends and family. let reflect further on that.

@nhc2000 Can you give me some more details and design on this in a new issue.

**Comment by mehtaakshay2206** [comment]
![auth0](https://user-images.githubusercontent.com/10251467/29238905-a02936d6-7f5c-11e7-88f8-5e4ee63cf6ba.png)
![auth0-2](https://user-images.githubusercontent.com/10251467/29238906-a02ee8ec-7f5c-11e7-9a4e-559d8f303721.png)


@nhc2000 I tried with the above credentials and not able to login. Then later when i tried again it said the account was blocked. Can you try registering again or can create account for another email.

**Comment by nhc2000** [comment]
I created a ticket for it and i'm expecting a response. Let try it when next we are online together.
