### ISSUE TITLE
Have a separate database for faithcanon

### ISSUE THREAD

**Issue by mehtaakshay2206** [nhc2000/FaithCanon#8]
- Clone the faithbooks database and rename it as faithcanon.
 - Change the database credentials in server code and
 - Deploy the code into EBS.

Estimation : 1 Hour.

**Comment by nhc2000** [comment]
I have just clean the DynamoDB table. I'm not sure which is your sign in credentials, but after cloning the databse and rename it, please make sure you remove too many of the test ID's. I want to start with clean database. let me know when it's done.

**Comment by mehtaakshay2206** [comment]
@nhc2000 Ok then instead of cloning data i just create a new database with index. Then we'll start with the fresh data itself

**Comment by mehtaakshay2206** [comment]
@nhc2000 Created new table "FaithCanonUsers".

**Comment by nhc2000** [comment]
Yes it's better to create a new table because there's no data there anyway.

**Comment by mehtaakshay2206** [comment]
@nhc2000 Yes created new table yesterday and deployed the code by pointing to new table.
All the above changes are done.
