### ISSUE TITLE
User profile update.

### ISSUE THREAD

**Issue by mehtaakshay2206** [nhc2000/FaithCanon#9]
@nhc2000 Can you provide UI design to view and edit user's profile so that i can start working on it.

**Comment by nhc2000** [comment]
i'm working on it.

Basit Oladapo


On ‎Friday‎, ‎August‎ ‎11‎, ‎2017‎ ‎12‎:‎56‎:‎57‎ ‎AM‎ ‎EDT, Akshay Mehta <notifications@github.com> wrote:


@nhc2000 Can you provide UI design to view and edit user's profile so that i can start working on it.

**Comment by nhc2000** [comment]
The group field should open menu script to fill up per instructions in the pdf provided.
